config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :activities
  devise_for :users

  namespace :api do
    devise_scope :user do
      post   "login",  to: "sessions#create"
      delete "logout", to: "sessions#destroy"
    end

    resources :activities, only: [ :index, :show ]

    resources :tasks, only: [ :index, :show ] do
      post :transition
    end
  end

  namespace :rui do
    get "about", to: "pages#about"
    get "pricing", to: "pages#pricing"
    get "dashboard", to: "pages#dashboard"
    get "projects", to: "pages#projects"
    get "project", to: "pages#project"
    get "messages", to: "pages#messages"
    get "message", to: "pages#message"
    get "assignments", to: "pages#assignments"
    get "calendar", to: "pages#calendar"
    get "people", to: "pages#people"
    get "profile", to: "pages#profile"
    get "activity", to: "pages#activity"
    get "settings", to: "pages#settings"
    get "notifications", to: "pages#notifications"
    get "billing", to: "pages#billing"
    get "team", to: "pages#team"
    get "integrations", to: "pages#integrations"
  end

  if Rails.env.development?
    # Visit the start page for Rails UI any time at /railsui/start
    mount Railsui::Engine, at: "/railsui"
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "pages/home"
  # Defines the root path route ("/")
  root "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :account
  belongs_to :user # creator
  has_many :tasks, dependent: :destroy
  has_many :activity_assignments, -> { order(:position) }, dependent: :destroy
  has_many :assignees, through: :activity_assignments, source: :user

  validates :name, presence: true
  validates :period, presence: true
  validates :frequency, numericality: { greater_than: 0 }
  validates :times_per_period, numericality: { greater_than: 0 }
  validate :valid_status_transition, on: :update
  validate :cannot_add_tasks_if_active, on: :update
  validate :immutable_fields_when_activity_active, on: :update

  enum :status, {
    draft: "draft",
    active: "active",
    archived: "archived"
  }

  enum :period, {
    day:   "day",
    week:  "week",
    month: "month"
  }

  enum :activity_type, {
    chore: "chore",
    habit: "habit",
    maintenance: "maintenance"
  }

  def activate!
    raise "Activity already active" if active?
    raise "No assignees defined" if assignees.empty?
    raise "Activity must have at least one task" if tasks.empty?

    Activities::TaskGenerator.new(self).generate!
    update!(status: :active)
  end

  def next_assignee(index)
    assignees[index % assignees.size]
  end

  def assignee_for(index)
    assignees[index % assignees.size]
  end

  def generate!
    Activities::TaskGenerator.new(self).generate!
  end

  def archive!
    raise "Only active activities can be archived" unless active?

    archived!
  end

  def next_assignee
    raise "No assignees defined" if activity_assignments.empty?

    last_task = tasks.order(created_at: :desc).first

    return activity_assignments.first.user unless last_task

    assignments = activity_assignments.to_a

    last_index = assignments.index do |assignment|
      assignment.user_id == last_task.assigned_to_id
    end
    # Safety fallback (override/manual assignment)
    return assignments.first.user if last_index.nil?

    next_assignment = assignments[last_index + 1] || assignments.first
    next_assignment.user
  end

  def generate_tasks!(from:, to:)
    raise "Activity must be active" unless active?
    raise "No assignees defined" if activity_assignments.empty?

    dates = generation_dates(from:, to:)

    dates.each do |date|
      next if tasks.exists?(due_on: date)

      Task.create!(
        activity: self,
        assigned_to: next_assignee,
        due_on: date
      )
    end
  end

  private

  def valid_status_transition
    return unless status_changed?

    from, to = status_change

    allowed = case from
    when "draft"    then %w[active]
    when "active"   then %w[archived]
    when "archived" then []
    else []
    end

    return if allowed.include?(to)

    errors.add(:status, "cannot transition from #{from} to #{to}")
  end

  def cannot_add_tasks_if_active
    return unless active?
    return unless tasks.any?(&:new_record?)

    errors.add(:tasks, "cannot be added once the activity is active")
  end

  def activity_must_be_active
    return if task.activity.active?

    errors.add(:base, "Cannot override task from inactive activity")
  end

  def immutable_fields_when_activity_active
    return unless active?

    immutable_fields = %i[
      period
      frequency
      times_per_period
    ]

    immutable_fields.each do |field|
      if will_save_change_to_attribute?(field)
        errors.add(field, "cannot be changed once the activity is active")
      end
    end
  end

  def generation_dates(from:, to:)
    case period.to_sym
    when :day
      (from..to).to_a
    when :week
      generate_weekly_dates(from, to)
    when :month
      generate_monthly_dates(from, to)
    else
      raise "Unknown period"
    end
  end

  def generate_weekly_dates(from, to)
    weeks = (from..to).group_by(&:cweek)

    weeks.flat_map do |_week, days|
      days.first(times_per_period)
    end
  end

  def generate_monthly_dates(from, to)
    months = (from..to).group_by { |d| [ d.year, d.month ] }

    months.flat_map do |_month, days|
      days.first(times_per_period)
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < AuthenticatedController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = current_account.activities
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = current_account.activities.new(activity_params)
    @activity.user = current_user

    if @activity.save
      redirect_to @activity, notice: "Activity was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice: "Activity was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy!

    redirect_to activities_path, notice: "Activity was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = current_account.activities.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.expect(activity: [ :name, :description, :user_id, :status, :period, :activity_type, :frequency, :times_per_period ])
    end
end

app/controllers/api/activities_controller.rb
module Api
  class ActivitiesController < Api::BaseController
    before_action :set_activity, only: %i[ show ]

    def index
      @activities = current_account.activities
      render json: @activities
    end

    def show
      render json: @activities
    end

    private

    def set_activity
      @activities = current_account.activities.find(params[:id])
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def static_stars(stars, max: 5)
    content_tag :div, class: "flex flex-row-reverse justify-end" do
      (1..max).to_a.reverse.map do |i|
        css = i <= stars.to_i ? "text-yellow-400" : "text-gray-300"

        content_tag :div, "★",
          class: "#{css} cursor-default transition-colors text-sm"
        end.join.html_safe
      end
  end
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= activity.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= activity.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1">User:</strong>
    <%= activity.user_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Status:</strong>
    <%= activity.status %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Period:</strong>
    <%= activity.period %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Activity type:</strong>
    <%= activity.activity_type %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Frequency:</strong>
    <%= activity.frequency %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Times per period:</strong>
    <%= activity.times_per_period %>
  </div>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity, builder: Railsui::FormBuilder) do |form| %>
  <%= render "rui/shared/error_messages", resource: form.object %>

  <div class="my-5">
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": activity.errors[:name].none?, "border-red-400 focus:outline-red-600": activity.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description, class: "block text-sm font-medium text-gray-700" %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": activity.errors[:description].none?, "border-red-400 focus:outline-red-600": activity.errors[:description].any?}] %>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div class="my-5">
      <%= form.select :activity_type, Activity.activity_types.keys.map { |activity_type| [activity_type.humanize, activity_type] }, { prompt: "Select Activity Type" }, { class: "form-select text-base" } %>
    </div>

    <div class="my-5">
      <%= form.select :period, Activity.periods.keys.map { |period| [period.humanize, period] }, { prompt: "Select Period" }, { class: "form-select text-base" } %>
    </div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div class="my-5">
      <%= form.number_field :frequency, { class: "form-input" } %>
    </div>

    <div class="my-5">
      <%= form.number_field :times_per_period, class: "form-input" %>
    </div>
  </div>

  <div class="my-5 grid grid-cols-1 md:grid-cols-2 gap-4">
    <div>
      <%= form.datetime_field :start_date, class: "form-input" %>
    </div>
    
    <div>
      <%= form.datetime_field :end_time, class: "form-input" %>
    </div>
  </div>

  <div class="my-5 flex items-center space-x-4 form-group">
    <%= form.select :status, Activity.statuses.keys.map { |status| [status.humanize, status] }, { prompt: "Select Status" }, { class: "form-select" } %>
  </div>

  <div class="my-5 flex flex-col-2">
    <div class="block mt-1 mr-2">Reward Stars:</div>
    <%= render StarRatingComponent.new(
      name: "activity[reward_stars]",
      value: activity.reward_stars
      ) %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/activities/_old_index.html.erb
<% content_for :title, "Activities" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Activities</h1>
    <%= link_to "New activity", new_activity_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="activities" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @activities.any? %>
      <% @activities.each do |activity| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render activity %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", activity, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_activity_path(activity), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", activity, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No activities found.</p>
    <% end %>
  </div>
</div>

app/views/activities/edit.html.erb
<% content_for :title, "Editing activity" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing activity</h1>

  <%= render "form", activity: @activity %>

  <%= link_to "Show this activity", @activity, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to activities", activities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/activities/index.html.erb
<% content_for :header do %>
  <%= render "rui/shared/admin/nav", { header_title: "Activities" } do %>
    <%#= render "rui/shared/admin/create_dropdown" %>
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-bold"><% content_for :title, "Activities" %></h1>
      <div>
        <%= link_to "+ Activity", new_activity_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="bg-white border-b dark:bg-slate-800/50 dark:border-b dark:border-slate-700 px-4">
  <div class="container mx-auto sm:flex flex-wrap justify-between items-center">
    <nav role="messages nav">
      <ul
        class="flex items-center justify-start sm:space-x-1 py-2 text-slate-600 sm:overflow-auto overflow-y-hidden scroll-smooth snap-start scrollbar-thin scrollbar-thumb-gray-200 scrollbar-track-gray-100/50 scrollbar-thumb-rounded">
        <li class="flex justify-center items-center sm:block">
          <%= link_to "#", class: "py-2 px-4 bg-slate-50 dark:bg-slate-900 rounded-lg transition ease-in-out duration-300 text-primary-600 dark:text-primary-400 font-medium flex items-center gap-2 dark:hover:bg-slate-900/80" do %>
            <span>Active</span>
            <span class="rounded bg-primary-600 text-white px-1 py-px text-xs font-semibold"><%= @activities.active.count %></span>
          <% end %>
        </li>
        <li class="flex justify-center items-center sm:block">
          <%= link_to "#", class: "py-2 px-4 rounded-lg transition ease-in-out duration-300 hover:bg-slate-50 hover:text-primary-600 dark:hover:text-primary-400 font-medium flex items-center gap-2 group dark:text-slate-300 dark:hover:bg-slate-900" do %>
            <span>Pending</span>
            <span class="rounded bg-slate-200 text-slate-500 px-1 py-px text-xs font-semibold"><%= @activities.draft.count %></span>
          <% end %>
        </li>
        <li class="flex justify-center items-center sm:block">
          <%= link_to "#", class: "py-2 px-4 rounded-lg transition ease-in-out duration-300 hover:bg-slate-50 hover:text-primary-600 dark:hover:text-primary-400 font-medium flex items-center gap-2 group dark:text-slate-300 dark:hover:bg-slate-900" do %>
            <span>Archived</span>
            <span class="rounded bg-slate-200 text-slate-500 px-1 py-px text-xs font-semibold"><%= @activities.archived.count %></span>
          <% end %>
        </li>
      </ul>
    </nav>

    <div class="sm:flex items-center sm:space-x-4">
      <form action="#">
        <label for="people_sort" class="sr-only">Filter results</label>
        <select class="form-select text-base" id="people_sort">
          <option value="">Active</option>
          <option value="1">Pending</option>
          <option value="1">Archived</option>
        </select>
      </form>

      <div class="relative lg:w-auto w-full lg:mt-0 md:mt-0 mt-4 sm:mt-0 lg:mb-0 mb-4">
        <%= icon "magnifying-glass", class: "size-5 text-slate-500/90 stroke-current absolute left-3 top-3" %>
        <input type="search" placeholder="Search" class="form-input lg:w-[250px] pl-10 focus:shadow-inner">
      </div>
    </div>
  </div>
</div>

<div class="container mx-auto px-4 my-16">
    <div class="container mx-auto rounded-lg border border-slate-300/80 shadow shadow-slate-100 dark:shadow-slate-950 mt-6 bg-white dark:bg-slate-800 dark:border-slate-600/80">
      <% if @activities.any? %>
        <ul class="divide-y divide-slate-300/80 dark:divide-slate-600">
          <li class="px-4 py-5 sm:text-base text-sm items-start grid grid-cols-2 sm:grid-cols-20 gap-3 sm:gap-0 before:content-[''] before:absolute relative before:left-2 before:h-[calc(100%-30px)] before:w-2 before:rounded-full before:bottom-1 before:top-4 pl-8 before:flex before:flex-col before:items-center before:justify-center hover:bg-slate-50 transition ease-in-out duration-200 dark:hover:bg-slate-800">
            <div class="sm:col-span-3 col-span-1">
              Name
            </div>
            <div class="sm:col-span-2 col-span-1">
              Type
            </div>
            <div class="sm:col-span-2 col-span-1">
              Period
            </div>
            <div class="sm:col-span-2 col-span-1">
              Freq
            </div>
            <div class="sm:col-span-2 col-span-1">
              TPP
            </div>
            <div class="sm:col-span-2 col-span-1">
              StartedAt
            </div>
            <div class="sm:col-span-2 col-span-1">
              EndAt
            </div>
            <div class="sm:col-span-2 col-span-1">
              Stars
            </div>
            <div class="">&nbsp;</div>
          </li>
          <% @activities.each do |activity| %>
            <li class="px-4 py-5 sm:text-base text-sm items-start grid grid-cols-2 sm:grid-cols-20 gap-3 sm:gap-0 before:content-[''] before:absolute relative before:left-2 before:h-[calc(100%-30px)] before:w-2 before:rounded-full before:bottom-1 before:top-4 pl-8 before:flex before:flex-col before:items-center before:justify-center hover:bg-slate-50 transition ease-in-out duration-200 dark:hover:bg-slate-800">
              <div class="sm:col-span-3 col-span-1">
                <%= activity.name %>
              </div>
              <div class="sm:col-span-2 col-span-1">
                <%= activity.activity_type %>
              </div>
              <div class="sm:col-span-2 col-span-1">
                <%= activity.period %>
              </div>
              <div class="sm:col-span-2 col-span-1">
                <%= activity.frequency %>
              </div>
              <div class="sm:col-span-2 col-span-1">
                <%= activity.times_per_period %>
              </div>
              <div class="sm:col-span-2 col-span-1">
                <%= activity.start_date %>
              </div>
              <div class="sm:col-span-2 col-span-1">
                <%= activity.end_time %>
              </div>
              <div class="sm:col-span-2 col-span-1">
                <%= static_stars(activity.reward_stars) %>
              </div>
              <div class="">
                <div data-controller="railsui-dropdown" class="sm:col-span-1 relative col-span-2">
                  <div class="flex justify-end">
                    <button data-action="click->railsui-dropdown#toggle click@window->railsui-dropdown#hide"
                      class="-mt-1 block group p-2 rounded-lg focus:ring-4 focus:ring-primary-50 dark:focus:ring-slate-600/50">
                      <%= icon "cog-6-tooth", class: "size-6 stroke-current text-slate-500 group-hover:text-primary-600 dark:group-hover:text-primary-400" %>
                    </button>
                  </div>

                    <ul data-railsui-dropdown-target="menu"
                      class="hidden transition transform origin-to-right absolute right-0 top-10 bg-white rounded-lg shadow-xl shadow-slate-900/10 border border-slate-200 md:w-[200px] w-full z-50 py-2 dark:bg-slate-700 dark:shadow-slate-900/50 dark:border-slate-500/60 md:text-sm text-base font-medium text-slate-600 dark:text-slate-200"
                      data-transition-enter-active="transition ease-out duration-300"
                      data-transition-enter-from="transform opacity-0 scale-95"
                      data-transition-enter-to="transform opacity-100 scale-100"
                      data-transition-leave-active="transition ease-in duration-300"
                      data-transition-leave-from="transform opacity-100 scale-100"
                      data-transition-leave-to="transform opacity-0 scale-95">
                      <li>
                        <%= link_to activity, class: "px-4 py-[.4rem] hover:text-primary-600 dark:hover:text-primary-300 group flex items-center justify-start gap-3" do %>
                          <%= icon "eye", class: "size-4" %>
                          <span>View</span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to edit_activity_path(activity), class: "px-4 py-[.4rem] hover:text-primary-600 dark:hover:text-primary-300 group flex items-center justify-start gap-3" do %>
                          <%= icon "pencil", class: "size-4" %>
                          <span>Edit</span>
                        <% end %>
                      </li>
                    </ul>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <li>
          <div colspan="3" class="px-4 py-2 text-sm text-gray-600">No activities found.</div>
        </li>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<% content_for :title, "New activity" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New activity</h1>

  <%= render "form", activity: @activity %>

  <%= link_to "Back to activities", activities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/activities/show.html.erb
<% content_for :title, "Showing activity" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing activity</h1>

  <%= render @activity %>

  <%= link_to "Edit this activity", edit_activity_path(@activity), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to activities", activities_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this activity", @activity, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>